// Code generated by "enumer -type Subscription -trimprefix Subscription -transform snake"; DO NOT EDIT.

package streaming

import (
	"fmt"
	"strings"
)

const _SubscriptionName = "option_tradesoption_quotesstock_barsstock_quotesstock_tradesnews"

var _SubscriptionIndex = [...]uint8{0, 13, 26, 36, 48, 60, 64}

const _SubscriptionLowerName = "option_tradesoption_quotesstock_barsstock_quotesstock_tradesnews"

func (i Subscription) String() string {
	i -= 1
	if i >= Subscription(len(_SubscriptionIndex)-1) {
		return fmt.Sprintf("Subscription(%d)", i+1)
	}
	return _SubscriptionName[_SubscriptionIndex[i]:_SubscriptionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SubscriptionNoOp() {
	var x [1]struct{}
	_ = x[SubscriptionOptionTrades-(1)]
	_ = x[SubscriptionOptionQuotes-(2)]
	_ = x[SubscriptionStockBars-(3)]
	_ = x[SubscriptionStockQuotes-(4)]
	_ = x[SubscriptionStockTrades-(5)]
	_ = x[SubscriptionNews-(6)]
}

var _SubscriptionValues = []Subscription{SubscriptionOptionTrades, SubscriptionOptionQuotes, SubscriptionStockBars, SubscriptionStockQuotes, SubscriptionStockTrades, SubscriptionNews}

var _SubscriptionNameToValueMap = map[string]Subscription{
	_SubscriptionName[0:13]:       SubscriptionOptionTrades,
	_SubscriptionLowerName[0:13]:  SubscriptionOptionTrades,
	_SubscriptionName[13:26]:      SubscriptionOptionQuotes,
	_SubscriptionLowerName[13:26]: SubscriptionOptionQuotes,
	_SubscriptionName[26:36]:      SubscriptionStockBars,
	_SubscriptionLowerName[26:36]: SubscriptionStockBars,
	_SubscriptionName[36:48]:      SubscriptionStockQuotes,
	_SubscriptionLowerName[36:48]: SubscriptionStockQuotes,
	_SubscriptionName[48:60]:      SubscriptionStockTrades,
	_SubscriptionLowerName[48:60]: SubscriptionStockTrades,
	_SubscriptionName[60:64]:      SubscriptionNews,
	_SubscriptionLowerName[60:64]: SubscriptionNews,
}

var _SubscriptionNames = []string{
	_SubscriptionName[0:13],
	_SubscriptionName[13:26],
	_SubscriptionName[26:36],
	_SubscriptionName[36:48],
	_SubscriptionName[48:60],
	_SubscriptionName[60:64],
}

// SubscriptionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SubscriptionString(s string) (Subscription, error) {
	if val, ok := _SubscriptionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SubscriptionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Subscription values", s)
}

// SubscriptionValues returns all values of the enum
func SubscriptionValues() []Subscription {
	return _SubscriptionValues
}

// SubscriptionStrings returns a slice of all String values of the enum
func SubscriptionStrings() []string {
	strs := make([]string, len(_SubscriptionNames))
	copy(strs, _SubscriptionNames)
	return strs
}

// IsASubscription returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Subscription) IsASubscription() bool {
	for _, v := range _SubscriptionValues {
		if i == v {
			return true
		}
	}
	return false
}
