{{ if .Values.nats.initJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-init
data:
    init.sh: |
        {{- .Files.Get "includes/init-nats.sh" | nindent 8 }}
    orders-stream.json: |
        {{- $ordersubj := printf "%s.orders.v0.*" .Values.nats.subjectPrefix }}
        {{- $ordersstream := dict
            "name" "nalpaca-orders-stream-v0"
            "description" "Nalpaca order stream. Push an order protobuf on this stream and the consumer will execute the trade"
            "subjects"  (list $ordersubj)
            "retention" "workqueue"
        }}
        {{ mustMerge $ordersstream .Values.orders.streamConfig .Values.nats.defaultStreamConfig | toJson }}
    orders-consumer.json: |
        {{- $ordersconsumer := dict
            "durable_name" "nalpaca-orders-consumer-v0"
            "description" "Nalpaca order stream consumer. Nalpaca will consume messages on this stream and send them."
            "filter_subject"  $ordersubj
        }}
        {{ mustMerge $ordersconsumer .Values.orders.consumerConfig .Values.nats.defaultConsumerConfig | toJson }}
    cancel-stream.json: |
        {{- $cancelsubj := printf "%s.cancel.v0.*" .Values.nats.subjectPrefix }}
        {{- $cancelstream := dict
            "name" "nalpaca-cancel-stream-v0"
            "description" "Nalpaca cancel stream. Push on this subject to cancel orders"
            "subjects"  (list $cancelsubj)
            "retention" "workqueue"
        }}
        {{ mustMerge $cancelstream .Values.cancel.streamConfig .Values.nats.defaultStreamConfig | toJson }}
    cancel-consumer.json: |
        {{- $cancelconsumer := dict
            "durable_name" "nalpaca-cancel-consumer-v0"
            "description" "Nalpaca cancel consumer. Listens to the cancel stream and cancels orders as they come in"
            "filter_subject"  $cancelsubj
        }}
        {{ mustMerge $cancelconsumer .Values.cancel.consumerConfig .Values.nats.defaultConsumerConfig | toJson }}
    tradeupdater-stream.json: |
        {{- $tradesubj := printf "%s.tradeupdater.v0.*" .Values.nats.subjectPrefix }}
        {{- $tradestream := dict
            "name" "nalpaca-tradeupdater-stream-v0"
            "description" "Nalpaca trade update stream. When a trade update is seen for the portfolio, nalpaca will push the update on the stream"
            "subjects"  (list $tradesubj)
            "retention" "workqueue"
        }}
        {{ mustMerge $tradestream .Values.tradeupdater.streamConfig .Values.nats.defaultStreamConfig | toJson }}
    tradeupdater-consumer.json: |
        {{- $tradeconsumer := dict
            "durable_name" "nalpaca-tradeupdater-consumer-v0"
            "description" "Nalpaca trade update consumer. Connect to this consumer to receive trade updates"
            "filter_subject"  $tradesubj
        }}
        {{ mustMerge $tradeconsumer .Values.tradeupdater.consumerConfig .Values.nats.defaultConsumerConfig | toJson }}
    stockstream-stream.json: |
        {{- $tradesubj := printf "%s.stockstream.v0.*" .Values.nats.subjectPrefix }}
        {{- $tradestream := dict
            "name" "nalpaca-stockstream-stream-v0"
            "description" "Nalpaca stock stream. Gives bar updates by the minute"
            "subjects"  (list $tradesubj)
            "retention" "workqueue"
        }}
        {{ mustMerge $tradestream .Values.stockstream.streamConfig .Values.nats.defaultStreamConfig | toJson }}
    stockstream-consumer.json: |
        {{- $tradeconsumer := dict
            "durable_name" "nalpaca-stockstream-consumer-v0"
            "description" "Nalpaca stock stream consumer. Connect to this consumer to receive bar updates by the minute"
            "filter_subject"  $tradesubj
        }}
        {{ mustMerge $tradeconsumer .Values.stockstream.consumerConfig .Values.nats.defaultConsumerConfig | toJson }}
{{ end }}