{{ if .Values.nats.initJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-init
data:
    init.sh: |
        {{- .Files.Get "includes/nats/init.sh" | nindent 8 }}
    stream.json: |
        {{- $x := .Files.Get "includes/nats/stream.json" | fromJson -}}
        {{ mustMerge .Values.nats.initJob.streamConfig $x | toJson | nindent 8 }}
    stock-order-create-consumer.json: |
        {{- $x := .Files.Get "includes/nats/stock-order-create-consumer.json" | fromJson -}}
        {{ mustMerge .Values.orders.consumerConfig $x | toJson | nindent 8 }}
    stock-order-cancel-consumer.json: |
        {{- $x := .Files.Get "includes/nats/stock-order-cancel-consumer.json" | fromJson -}}
        {{ mustMerge .Values.cancel.consumerConfig $x | toJson | nindent 8 }}
    trade-updater.json: |
        {{- $x := .Files.Get "includes/nats/trade-updater.json" | fromJson -}}
        {{ mustMerge .Values.tradeupdater.consumerConfig $x | toJson | nindent 8 }}
    stock-bars-consumer.json: |
        {{- $x := .Files.Get "includes/nats/stock-bars-consumer.json" | fromJson -}}
        {{ mustMerge .Values.stockstream.consumerConfig.bars $x | toJson | nindent 8 }}
    stock-quotes-consumer.json: |
        {{- $x := .Files.Get "includes/nats/stock-quotes-consumer.json" | fromJson -}}
        {{ mustMerge .Values.stockstream.consumerConfig.quotes $x | toJson | nindent 8 }}
    stock-trades-consumer.json: |
        {{- $x := .Files.Get "includes/nats/stock-trades-consumer.json" | fromJson -}}
        {{ mustMerge .Values.stockstream.consumerConfig.trades $x | toJson | nindent 8 }}
    news-consumer.json: |
        {{- $x := .Files.Get "includes/nats/news-consumer.json" | fromJson -}}
        {{ mustMerge .Values.newsstream.consumerConfig $x | toJson | nindent 8 }}
    option-quotes-consumer.json: |
        {{- $x := .Files.Get "includes/nats/option-quotes-consumer.json" | fromJson -}}
        {{ mustMerge .Values.optionstream.consumerConfig.quotes $x | toJson | nindent 8 }}
    option-trades-consumer.json: |
        {{- $x := .Files.Get "includes/nats/option-trades-consumer.json" | fromJson -}}
        {{ mustMerge .Values.optionstream.consumerConfig.trades $x | toJson | nindent 8 }}
{{ end }}