{{ if .Values.nats.initJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-init
data:
    init.sh: |
        {{- .Files.Get "includes/init-nats.sh" | nindent 8 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: action-stream-conf
data:
    action-stream.json: |
        {{- $x := .Files.Get "includes/nats/action/stream.json" | fromJson -}}
        {{ mustMerge .Values.nats.actionStream $x | toJson | nindent 8 }}
    orders-consumer.json: |
        {{- $x := .Files.Get "includes/nats/action/order-consumer.json" | fromJson -}}
        {{ mustMerge .Values.orders.consumerConfig $x | toJson | nindent 8 }}
    cancel-consumer.json: |
        {{- $x := .Files.Get "includes/nats/action/cancel-consumer.json" | fromJson -}}
        {{ mustMerge .Values.cancel.consumerConfig $x | toJson | nindent 8 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-stream-conf
data:
    data-stream.json: |
        {{- $x := .Files.Get "includes/nats/data/stream.json" | fromJson -}}
        {{ mustMerge .Values.nats.dataStream $x | toJson | nindent 8 }}
    stock-consumer.json: |
        {{- $x := .Files.Get "includes/nats/data/stock-consumer.json" | fromJson -}}
        {{ mustMerge .Values.stockstream.consumerConfig $x | toJson | nindent 8 }}
    trade-update-consumer.json: |
        {{- $x := .Files.Get "includes/nats/data/trade-update-consumer.json" | fromJson -}}
        {{ mustMerge .Values.tradeupdater.consumerConfig $x | toJson | nindent 8 }}
{{ end }}