services:
  nats:
    image: nats:latest
    ports:
      - 4225:4222
    command: "--js"

  natsbox:
    image: docker.io/natsio/nats-box:latest
    volumes:
      - ./nats-init.sh:/bin/init.sh
    command: "sh /bin/init.sh"
    depends_on:
      - "nats"

  server:
    image: server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      DISABLE_TRACING: "true"
      DISABLE_METRICS: "true"
      DISABLE_HEALTH: "true"
      NATS_URL: nats://nats:4222
    depends_on:
      - natsbox
